CREATE TABLE IF NOT EXISTS FINAL_NOTE (
    ID text,
    TITLE text,
    DESCRIPTION text,
    CREATE_TS DATETIME DEFAULT CURRENT_TIMESTAMP
    TAG_ID text
)^

CREATE TABLE IF NOT EXISTS FINAL_TAG (
    ID text,
    NAME text
)^