CREATE TABLE IF NOT EXISTS FINAL_NOTE (
    ID text,
    TITLE text,
    DESCRIPTION text,
    CREATE_TS DATETIME DEFAULT CURRENT_TIMESTAMP
)^

INSERT INTO FINAL_NOTE (ID, TITLE, DESCRIPTION, CREATE_TS) VALUES ('f6aa5261-3b41-4003-8eaf-0b6b811f9687', 'На работу в четверг', 'Мне нужно в чт на работу, сказали что срочно', CURRENT_TIMESTAMP)^
INSERT INTO FINAL_NOTE (ID, TITLE, DESCRIPTION, CREATE_TS) VALUES ('56c99665-44cf-4de3-b68f-1ee5bdaa1b3e', 'На тренировку', 'Не забыть бы сходить', CURRENT_TIMESTAMP)^
INSERT INTO FINAL_NOTE (ID, TITLE, DESCRIPTION, CREATE_TS) VALUES ('8b1fcb3b-a114-4994-a7b5-1f6955168180', 'Работать лучше дома', 'Сиди и работай дома', CURRENT_TIMESTAMP)^