CREATE TABLE IF NOT EXISTS FINAL_REMINDER_NOTE (
    ID text,
    NOTE_ID text,
    LOOP INTEGER,
    TYPE text
)^

CREATE TABLE IF NOT EXISTS FINAL_REMINDER_DATE (
    ID text,
    NOTE_ID text,
    DATE_ DATETIME DEFAULT CURRENT_TIMESTAMP
)^

CREATE TABLE IF NOT EXISTS FINAL_REMINDER_DAY (
    ID text,
    NOTE_ID text,
    DAY_ DATETIME DEFAULT CURRENT_TIMESTAMP
)^

CREATE TABLE IF NOT EXISTS FINAL_REMINDER_HOUR (
    ID text,
    DAY_ID text,
    HOUR_ DATETIME DEFAULT CURRENT_TIMESTAMP
)^
